function(truffle_target_warnings target)
    if(MSVC)
        target_compile_options(${target} PRIVATE /W4 /EHsc /permissive-)
        if(TRUFFLE_WARNINGS_AS_ERRORS)
            target_compile_options(${target} PRIVATE /WX)
        endif()
        return()
    endif()

    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    if(TRUFFLE_WARNINGS_AS_ERRORS)
        target_compile_options(${target} PRIVATE -Werror)
    endif()
endfunction()
